### ISSUE TITLE
escape %

### ISSUE THREAD

**Issue by rogeriojlle** [mudrd8mz/node-moodle-client#13]
How do I format this?
```
wsfunction: "core_user_get_users",
  args : {
    email : '\%' // or '%' not work
  }
}
```

**Comment by mudrd8mz** [comment]
What are you trying to actually achieve?

**Comment by rogeriojlle** [comment]
A list with all users

**Comment by mudrd8mz** [comment]
So just do not specify any search criteria. But note what the code comment says:

> You can search without criteria, but the function is not designed for it. It could very slow or timeout. The function is designed to search some specific users.

Also, if you wanted to use some criteria, they must be passed differently - as an array of objects with properties "key" and "value".

In either case, this does not seem to be the client code issue and I would suggest to close this.

**Comment by rogeriojlle** [comment]
you are right
