### ISSUE TITLE
Did you name your project the same as the dependency you're installing?

### ISSUE THREAD

**Issue by alrashidmtz** [mudrd8mz/node-moodle-client#17]
I am trying to install moodle-client with npm, but an error ocurre

```bash
npm ERR! Refusing to install package with name "moodle-client" under a package
npm ERR! also called "moodle-client". Did you name your project the same
npm ERR! as the dependency you're installing?
```

**Comment by mudrd8mz** [comment]
So ... did you name your project the same as the dependency you're installing?

**Comment by Johndo** [comment]
I got the same error (just getting into web dev) Yes I did notice the name of the project was the same as the dependency (I downloaded a git project- https://github.com/chenqingspring/ng-lottie#installation using (git pull) and ran"npm install --save ng-lottie" in the home dir.)  can u please help me understand what's going on ?

**Comment by FrancoSecchi** [comment]
You need to enter the package.json file, and you change the name of the project
