### ISSUE TITLE
Is this repository support for nodejs?

### ISSUE THREAD

**Issue by robertgoncalvesbatista** [mudrd8mz/node-moodle-client#18]
I'd like to know if this repository is a support for NodeJS.

**Comment by mudrd8mz** [comment]
Hi. Thank you for your interest in this repository. I am not sure I fully understand your question though.

This repository provides a Node.js library that can be used to develop custom clients for the Moodle (https://moodle.org) web services.

Hope this helps.

**Comment by robertgoncalvesbatista** [comment]
Hi. I'm programming a application with NodeJS, I'd like to know if your repository will help me.

**Comment by mudrd8mz** [comment]
Aha.

**Comment by robertgoncalvesbatista** [comment]
I got it, thanks

**Comment by robertgoncalvesbatista** [comment]
I got it, thanks
