### ISSUE TITLE
self.protocol.METHODS is undefined when specifying POST in settings

### ISSUE THREAD

**Issue by ishtartec** [mudrd8mz/node-moodle-client#4]
Line 263:

``` javascript
                || self.protocol.METHODS.indexOf(settings.method) == -1) {
```

TypeError: Cannot call method 'indexOf' of undefined
    at client.call (/XXX/node_modules/moodle-client/client.js:263:42)

``` javascript
c.call({wsfunction: "core_user_view_user_list",
        arguments: {
            "courseid": 1
        },
        settings: {
            "method": "POST"
        }
```

Thanks!

**Comment by mudrd8mz** [comment]
Hey thanks! Will look at this next once I'm back from some travelling around the world.

**Comment by mudrd8mz** [comment]
This should be fixed now, thanks for the report!
