### ISSUE TITLE
Allow self signed certificates for development

### ISSUE THREAD

**Issue by ishtartec** [mudrd8mz/node-moodle-client#5]
When connecting to a moodle server using https, if the certificate is a self signed certificate, the connection will complain and will throw an error.

Adding the next line to the options object will allow self signed certificates. It would be great if it is something we can define on the settings:

``` javascript
var options = {
            hostname: self.host.hostname,
            port: self.host.port,
            path: self.host.pathname + "/webservice/rest/server.php?" + query,
            rejectUnauthorized: false
        }
```

I can make a PR if you wish.

Thanks!

**Comment by mudrd8mz** [comment]
Hey thanks! Will look at this next once I'm back from some travelling around the world. PR will be appreciated indeed.

**Comment by mudrd8mz** [comment]
Done. The `call` method now supports `options.settings.sslverify` parameter (true by default). If set to false, failed server SSL verification no longer emits an error event.

**Comment by mudrd8mz** [comment]
The API for this has changed in 0.4.0. Among other things, having the flag in call() only still did not allow to authenticate.
